### ISSUE TITLE
Diagram structure question

### ISSUE THREAD

**Issue by jamievicary** [NickHu/homotopy-core#13]
Why don't we define diagrams like this:
````
data Diagram = Diagram0 Generator | DiagramN Diagram (List Cospan)
````
I'm not saying I think this would be better, I'd just like to understand the design decisions.

**Comment by NickHu** [comment]
This decision is was made for code organisation reasons rather than any kind of technical advantage. If we took this approach, there would be no `DiagramN` type.

Many functions in the Diagram module only make sense on higher dimensional diagrams, so having their domain of type `DiagramN` (of which all terms are of the form `InternalDiagram ...`, using the constructor in the `newtype`) is a neat way to convey that (the alternative with your approach would be to mark these functions as `Partial`, and currently what this conveys is that a function might result in a runtime exception if supplied with arguments which type-check but are erroneous input - semantically, this is rather different).

**Comment by zrho** [comment]
The functions that operate only on higher dimensional diagrams are the
motivation for this split, which might be the best we can do given
purescript's lack of GADTs. We might introduce type classes to allow
functions that operate on Diagrams to take DiagramNs as well. I am also not
quite content with the name yet.

There is a happy side effect that we can hide the internals of the
InternalDiagram newtype. This is the space where we can introduce cached
information like a hash value or a maximum dimensional generator. Rewrites
or cones might also be annotated by such cached values, to avoid traversals
for some especially common operations.

**Comment by jamievicary** [comment]
Makes sense, thanks.
